name: MineralGenerator
main: me.mineralgenerator.MineralGeneratorPlugin
version: 1.0
api-version: 1.8.8
author: Filip
commands:
  mineralgenerator:
    description: Comando principale per il plugin MineralGenerator
    usage: /<command> reload
    aliases: [mg]
description: Plugin per generare minerali in chest tramite macchinari personalizzati.
